// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/hanariu/hanariu/pkg/hanariu"
	atoms "github.com/hanariu/hanariu/pkg/hanariu/atoms"
	icons "github.com/hanariu/hanariu/pkg/hanariu/icons"
	partials "starter/internal/partials"
)

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex flex-col w-full\"><div class=\"mt-16 sm:mt-20 lg:mt-40 lg:w-1/2 mx-auto flex justify-center\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = atoms.ThemeSwitcher(&atoms.ThemeSwitcherBosons{Size: "md"}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><h1 class=\"block text-center text-3xl font-bold text-secondary-800 sm:text-4xl md:text-5xl lg:text-6xl dark:text-primary-50 mt-10 lg:w-1/2 mx-auto\">Hello world!</h1><h2 class=\"text-center mt-6 text-lg text-secondary-800 dark:text-primary-100 dark:opacity-85 lg:w-1/2 mx-auto\">This is basic template of Hanariu -  Templ Atomic Design System. Build better UI for your Golang apps.</h2><div class=\"lg:w-1/2 mx-auto\"><div class=\"mt-8 lg:mt-8 flex flex-col items-center gap-4 sm:flex-row sm:gap-3 justify-center\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = atoms.Button(
				&atoms.ButtonBosons{
					Tag:   "a",
					Size:  "xl",
					Title: "Github repository",
					Attrs: hanariu.Attrs{
						"href": "https://github.com/hanariu/hanariu",
					},
				},
			).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var3 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
				templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
				if !templ_7745c5c3_IsBuffer {
					defer func() {
						templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err == nil {
							templ_7745c5c3_Err = templ_7745c5c3_BufErr
						}
					}()
				}
				ctx = templ.InitializeContext(ctx)
				templ_7745c5c3_Err = icons.IconArrowRight().Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				return nil
			})
			templ_7745c5c3_Err = atoms.ButtonIcon(
				&atoms.ButtonBosons{
					Reverse: true,
					Tag:     "a",
					Size:    "xl",
					Title:   "Read more",
					Light:   true,
					Attrs: hanariu.Attrs{
						"href": "https://hanariu.dev",
					},
				},
			).Render(templ.WithChildren(ctx, templ_7745c5c3_Var3), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div class=\"mt-12 sm:mt-24 lg:mt-12 flex flex-col w-full\"><span class=\"flex justify-center w-full text-center md:text-left text-xs font-medium text-secondary-500 uppercase dark:text-secondary-200\">Created with:</span><div class=\"mt-10 gap-x-8 flex flex-wrap lg:flex-nowrap items-center gap-y-4 justify-center mx-auto w-full\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = atoms.ButtonLink(
				&atoms.ButtonLinkBosons{
					Tag:   "a",
					Color: "secondary",
					Title: "Golang",
					Attrs: hanariu.Attrs{
						"href": "https://go.dev",
					},
				},
			).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = atoms.ButtonLink(
				&atoms.ButtonLinkBosons{
					Tag:   "a",
					Color: "secondary",
					Title: "Templ",
					Attrs: hanariu.Attrs{
						"href": "https://templ.guide",
					},
				},
			).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = atoms.ButtonLink(
				&atoms.ButtonLinkBosons{
					Tag:   "a",
					Color: "secondary",
					Title: "Alpine",
					Attrs: hanariu.Attrs{
						"href": "https://alpinejs.dev",
					},
				},
			).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = atoms.ButtonLink(
				&atoms.ButtonLinkBosons{
					Tag:   "a",
					Color: "secondary",
					Title: "TypeScript",
					Attrs: hanariu.Attrs{
						"href": "https://www.typescriptlang.org",
					},
				},
			).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = atoms.ButtonLink(
				&atoms.ButtonLinkBosons{
					Tag:   "a",
					Color: "secondary",
					Title: "Vite",
					Attrs: hanariu.Attrs{
						"href": "https://vite.dev",
					},
				},
			).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = atoms.ButtonLink(
				&atoms.ButtonLinkBosons{
					Tag:   "a",
					Color: "secondary",
					Title: "Tailwind",
					Attrs: hanariu.Attrs{
						"href": "https://tailwindcss.com",
					},
				},
			).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><div class=\"mt-6 sm:mt-12 lg:mt-6 flex flex-col w-full\"><span class=\"flex justify-center w-full text-center md:text-left text-xs font-medium text-secondary-500 uppercase dark:text-secondary-200\">By:</span><div class=\"mt-4 mb-6 flex justify-center mx-auto w-full\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = atoms.ButtonLink(
				&atoms.ButtonLinkBosons{
					Tag:   "a",
					Size:  "lg",
					Color: "primary",
					Title: "Pay For Done",
					Attrs: hanariu.Attrs{
						"href": "https://payfordone.com",
					},
				},
			).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = partials.SectionContainer().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
